### ISSUE TITLE
IDEA: Split core logic and file type renovation

### ISSUE THREAD

**Issue by reicheltp** [singapore/renovate#1030]
Currently the code to renovate a special file type (like Dockerfile) is spread across multiple folders and files which makes it difficult to modify and / or add new file types.

Maybe, we could consider separating the core renovation logic from the renovation methods which are unique to a file, a similar way it's done with the apis for gitlab / github.

Then we could end with a single file and methods like `extractDependencies`, `updateDependency` etc.

**Comment by rarkins** [comment]
@reicheltp I think this is a good idea. Although we now support kind of 3 renovation "types" (npm, meteor, docker), meteor piggybacks on npm and docker is only partially complete, so there hasn't been a strong need to properly restructure things.

What if we structure it like `lib/managers/npm`, `lib/managers/meteor` and `lib/managers/docker`?
 I'm not 100% sure on that naming though, although I suppose it's easy to rename it later. For example later we may find the need to separate Dockerfile and docker-compose.yml detection and updating, although the upgrade resolution logic would be shared.

**Comment by rarkins** [comment]
Thinking some more, we have a few concepts:
- "package files": package.json, package.js (Meteor). Dockerfile, docker-compose.yaml, requirements.txt, etc
- "client": e.g. `npm` and `yarn` are separate clients
- "registry" (type): npm is also a type of registry, so too is docker
- "registry host": e.g. docker hub is a registry host, but so too is AWS's compatible one, quay.io, etc

We can't always map package file to client, but we can usually map client to package file (e.g. npm -> package.json, yarn -> package.json). But realistically we need to be prepared for some many-to-many scenarios too. e.g. the way we would "detect" yarn is because of presence of `yarn.lock`, not because of anything in the `package.json`.

So far we can always map client -> registry e.g. npm -> npm, yarn -> npm, docker -> docker, docker compose -> docker, pip -> pypi.

The "registry" is today combined into the `lib/api` group, e.g. we have `lib/api/npm` and `lib/api/docker` side by side with github and gitlab.

I still think it's a good idea although now I predict a pretty massive refactoring as a majority of functionality will move into these new subdirectories and the core will be mostly glue.

**Comment by rarkins** [comment]
@reicheltp this is quite a big task, so I've tried taking it in steps and aiming for good not perfect for now. I will keep this as an ongoing task so if you start work on any issues then always give me a heads up so I can aim not to conflict with you.

You can see a lot of logic has been moved from lib/workers to lib/manager: https://github.com/singapore/renovate/tree/master/lib/manager

In particular, all the *important* Docker logic has been moved into lib/manager/docker. It's not quite self-documenting but you can hopefully work out where to make changes.

**Comment by rarkins** [comment]
FYI I'm still doing some major refactoring to better enable this type of extensibility

**Comment by rarkins** [comment]
The split is mostly done, although refactoring later could still improve it.
