### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by IGZgustavomarin** [singapore/renovate#1055]
/rant-mode-on/
I'm having a lot of troubles keeping up with so many changes on `renovate`. I know that you are doing lot of work to improve it and this may be seen as an unfair complain. But the last months I have the feeling that I get more work trying to make `renovate` to work than if I do the updates manually. _I see a more and more  features but less stability and backward compatibility._
/rant-mode-off/

I'd like to have a simple setup to check several repos and create *a single commit* on each one with all changes to `package.json` and `package-lock.json`. That's it. I don't need to setup any scheduler. I don't need to check on docker, just my `npm` dependencies.

Can you help me create this simple config for my needs? Thanks you very much!

**Comment by rarkins** [comment]
Sorry about instability. Some have been on Renovate's side but it's been made a lot worse by GitLab's APIv3 to APIv4 changes, which were not very graceful.

Happy to help with a config for you and will get back soon

**Comment by rarkins** [comment]
Actually I have some questions already. I think the main requirements you have are:
  - Single branch/PR for all dependencies
  - Renovate only npm and not other package managers

I need to know though if you want all dependencies in package.json pinned, or just the devDependencies?

**Comment by rarkins** [comment]
Another question: do you want to update `package-lock.json` even if `package.json` hasn't change, or only update it when `package.json` changes? As you probably remember, we have the concept of "lock file maintenance" which is usually in a separate PR, which breaks your "single branch" requirements.

**Comment by rarkins** [comment]
Here's a config that matches the given requirements:
```
{
  "extends": [
    ":onlyNpm",
    "group:all"
  ]
}
```

Regarding stability, please make sure to stick with version 9.x for now and not the new 10.x. If you install via npm then 9.x is tagged as latest so you don't need to do anything differently. If you git clone then make sure to checkout the `9x` branch before deploying.

**Comment by IGZgustavomarin** [comment]
I'll try that config, thanks.

I'd like to update `package-lock.json` only if there is any change to `package.json` and regarding version pinning, I prefer to pin both deps and devDeps. 

Maybe I missed something regarding the lock. I'll get two PR even if I group all deps? How should I merge then? first the package change and then the lock file maintenance PR? or viceversa?

**Comment by IGZgustavomarin** [comment]
This is my complete config. I've just ran it with `renovate@9.99.0` and got a PR `renovate/pin-docker-digests` and several PRs for each outdated dependency. 

```
module.exports = {
  "extends": [
    ":onlyNpm",
    "group:all"
  ],
  platform: 'gitlab',
  endpoint: 'https://gitlab.xxxx.io/api/v4',
  onboarding: false,
  reviewers: [ 8 ], 
  logLevel: 'debug',
  labels: ['upgrade'],
  ignoreDeps: ['cucumber', 'restify', 'mocha', 'nock'],
  repositories: [
    // Service repositories
    'services/some-service',
  ]
}
```
What's missing or wrong? my run command is:
 `RENOVATE_CONFIG_FILE=$PWD/config.js renovate --log-level=debug`

**Comment by rarkins** [comment]
That's really strange - I tested that config on one of my own repositories before pasting it here, verifying:
- lock file maintenance was disabled
- docker was disabled
- only one branch was shared between the dependencies


I see you have log level already set to debug - can you provide me that output? (email is fine - rhys@arkins DOT net).

**Comment by rarkins** [comment]
@IGZgustavomarin sorry, I think I've confirmed that the problem is related to how that config file is being read. I've been able to reproduce on a test repository so can look at my own debug file.

**Comment by IGZgustavomarin** [comment]
Thanks, because to get the file I'd have to run it again and generate new PRs.

**Comment by rarkins** [comment]
Very sorry again! Specifically, the problem is with config presets, i.e. the `extends` array I gave you to try to shorten things. Long story short but the `extends` array doesn't get the right precedence only if loaded via the `config.js` as it was designed for `renovate.json`. Best thing you can do for now is use this config instead:

```
module.exports = {
  platform: 'gitlab',
  endpoint: 'https://gitlab.xxxx.io/api/v4',
  onboarding: false,
  docker: {
    enabled: false,
  },
  meteor: {
    enabled: false,
  },
  lockFileMaintenance: {
    enabled: false,
  },
  groupName: 'all',
  reviewers: [ 8 ], 
  logLevel: 'debug',
  labels: ['upgrade'],
  ignoreDeps: ['cucumber', 'restify', 'mocha', 'nock'],
  repositories: [
    // Service repositories
    'services/some-service',
  ]
}
```

It's same logic as earlier but configured with longer/traditional config. i.e. disable docker, meteor and lock file maintenance, and set groupName to 'all'.

FYI, Renovate should always "clean up" for itself, i.e. delete any `renovate/*` branches that aren't meant to be there.

**Comment by IGZgustavomarin** [comment]
Thanks, this seems to get my config back on track. 

Still no labels or assignees, but I guess that related to Gitlab APIv4. But I can live with that. 

Splitting into dev and latest tag would give users time to adapt. Thank you very much.

**Comment by rarkins** [comment]
Thanks for your patience. Gitlab labels/assignees will be fixed in 10.x as we have deprecated the v3 API there and refactored how/when labels are added to PRs. Please subscribe to https://github.com/singapore/renovate/issues/1075 to be notified when we think that feature has had adequate testing.

Re: dev/latest tag, that's essentially what I did - but via *npm*. i.e. 9.x is latest, 10.x is next. What I forgot to consider is that some people are getting Renovate via github instead of npm, where there isn't really the concept of release tracks natively. In future if I have the same requirement then I'll keep master as 'latest' and use another branch as 'next' so that you clone stable by default.
