### ISSUE TITLE
New version not detected if the package is in the same lerna monorepo

### ISSUE THREAD

**Issue by CPatchane** [singapore/renovate#1147]
Hi @rarkins, very nice job for renovate, I am using it in one of my projects https://github.com/CPatchane/create-cozy-app which is a monorepo and it works great 🎉

I just noticed something that seems to be a bug:
I have two packages in my monorepo `eslint-config-cozy-app` and `babel-preset-cozy-app` which are used as dependencies by my main package `cozy-scripts`. When I release a new version for all (using `lerna publish`), I expect to get new PRs from renovate to update `eslint-config-cozy-app` and `babel-preset-cozy-app` in my package `cozy-scripts` but it never happens. Even now, I just released new packages, I try renovate locally and it didn't see new  `eslint-config-cozy-app` and `babel-preset-cozy-app` packages.

I don't see any configurations about that, is it a wanted behaviour? Or maybe I am doing something wrong so I opened this issue to get answers.

Thanks!

**Comment by rarkins** [comment]
It's a deliberate feature - detect all package names within lerna and ignore them. I don't remember exactly what led me to add that but originally when adding lerna support it seemed necessary. Now I'm wondering if I should change it from always ignore to never ignore, or if it can be detected, or if it needs to be configured. Until I'm sure I may need to make it configurable so that you can get a fix.

**Comment by rarkins** [comment]
Noticed a couple of things. You have independent versioning, maybe that's something for Renovate to look at. Also I see you use yarn but not actually yarn workspaces?

**Comment by CPatchane** [comment]
Cool! That could be great to have it configurable, I would be able to test it 👍 

Yes, it's independent versioning and I don't use yarn workspaces for now but it could change for this last point. Does renovate take into account packages from yarn workspaces?

**Comment by rarkins** [comment]
Renovate supports both lerna and workspaces. In workspaces, the extra "work" is that Renovate needs to be smart enough to know to update the root `yarn.lock` whenever *any* `package.json` changes.

**Comment by rarkins** [comment]
@CPatchane I'm still a little confused here, trying to find out for sure what lerna's behaviour is. If you look at this issue, for example: https://github.com/lerna/lerna/issues/1018, then it sounds like lerna will update other (internal) packages with the new version automatically. i.e. this is why I disable Renovate trying to do it.

Also, you mentioned:
> I have two packages in my monorepo eslint-config-cozy-app and babel-preset-cozy-app which are used as dependencies by my main package cozy-scripts.

Actually, it looks like you have them as dependencies inside a `template` folder of your main package `cozy-scripts`. I wonder if this is having an impact on learna and/or Renovate too. When I use globtester.com it confirms that this `template` subdirectory is not captured by your `"packages/*"` glob in `lerna.json`:

![image](https://user-images.githubusercontent.com/6311784/32696409-c5dcf940-c777-11e7-8c18-ef0dde25954d.png)

If that "template" subdirectory can be moved up into `packages/` (e.g. into `packages/cozy-scripts-template`) then maybe `lerna` might update the versions for you whenever you `lerna publish`?

**Comment by rarkins** [comment]
@CPatchane I think I now understand the problem

Normally, `lerna` would patch the versions in `package.json` for any "internal" packages it published. i.e. no need for Renovate to do anything for them because they are updated in other `package.json` files at the same time they're published.

In your case, you have the `template/` subdirectory which means it doesn't match the `packages` array in `lerna.json` and hence `lerna` ignores it and *does not* patch it, meaning Renovate needs to.

I am fixing Renovate so that it uses the same logic as `lerna` to decide which `package.json` files are ignored. That way, it should start patching your template without you making any configuration changes.

However, you perhaps would be better off by putting the template under lerna's control, either by:

1. Moving it up into the `packages/` dir, or
2. Adding `cozy-scripts/packages/*` to your `packages` array in `lerna.json`. I assume this should work, but not certain

**Comment by rarkins** [comment]
@CPatchane Renovate fix now implemented and two new PRs have been raised in your repo:
![image](https://user-images.githubusercontent.com/6311784/32697614-bf8f3fd6-c794-11e7-9c07-47faba800726.png)

**Comment by CPatchane** [comment]
Wow I didn't expect a fix so quickly 🎊🎊

In fact, I didn't want to use the template as a package since I never want it published on npm or tagged and I wanted to avoid make it a private package if possible. It's why I didn't handle it with lerna (and it's itself inside a package) but I want to use renovate on it to keep all dependencies up to date. And that work well except for packages inside the monorepo until now.

I agree with your fix and since you check if it's matching a glob, I think that will be better for renovate usage :)

Thanks a lot @rarkins! 😃

**Comment by rarkins** [comment]
Can't you just set it to `private: true` in `package.json` to prevent publishing?

**Comment by CPatchane** [comment]
I could and I think I will give it a try. It could be better in the future to maintain.

**Comment by rarkins** [comment]
And yes it was the right thing to do for Renovate anyway because it allows for other ways people might mix lerna and non-lerna in the same repo.

**Comment by CPatchane** [comment]
OK, I remember why I was preferred this way. With private package lerna won't publish the package to npm but it will still increment the version and push a new git tag. And I don't want that, my `template` package here is just an template to bootstrap an application and I don't to push a tag for it or versioning it with semver (the bootstrapped application will always start at 0.1.0 version). But since it's an application with dependencies, I want to keep these dependencies updated thanks to renovate. 
This is a particular usage I agree :)
