### ISSUE TITLE
Can't get Merge Request list from Gitlab Platform

### ISSUE THREAD

**Issue by ManRueda** [singapore/renovate#1164]
When tries to get the Merge Requests list, use the state param with the value `open` but Gitlab only supports the value `opened`.

https://github.com/singapore/renovate/blob/d2cd755f3704bb69c551549cf3be6f82edcedb43/lib/workers/repository/onboarding/branch/check.js#L39

**Comment by rarkins** [comment]
Thank you for the bug report. I have confirmed from the GitLab API:
![image](https://user-images.githubusercontent.com/6311784/32747058-e5700752-c8b7-11e7-8e09-8c3a5597ae5e.png)

I think the best way to fix this is to implement the same `getPrList()` concept in GitLab that we have in GitHub, and massage the data so that `merged` is rewritten to `closed` and `opened` is rewritten to `open`.
