### ISSUE TITLE
8.21.5 breaks CI build

### ISSUE THREAD

**Issue by daprahamian** [singapore/renovate#196]
I am getting the following error:

```
00:12:20 debug: initRepo(keystone/keystone)
00:12:21 debug: keystone/keystone default branch = master
00:12:21 debug: No renovate.json found
00:12:21 debug: Checking if repo is configured
00:12:21 debug: Repo is configured or onboarding disabled
00:12:21 verbose: Can't find multiple package.json files in GitLab
00:12:21 info: Processing keystone/keystone package.json
00:12:22 error: Response code 401 (Unauthorized)
```

Because of this, it is only running renovate on the first listed package, and not running it on any other packages.

I do not see this error on `8.21.3`

Platform is gitlab

**Comment by rarkins** [comment]
By "CI build" you mean your own CI, not renovate's CI build on CircleCI, right?

**Comment by daprahamian** [comment]
@rarkins yes, my own CI build.

**Comment by rarkins** [comment]
Also, could you try 8.21.4 to help narrow it down?

**Comment by rarkins** [comment]
The list of commits is here: https://github.com/singapore/renovate/commits/master
I'm wondering if it was caused by this dependency update: https://github.com/singapore/renovate/commit/807f71a3cfe572a519a25e467b8bb80e105de3b8

**Comment by daprahamian** [comment]
@rarkins 8.21.4 also gives me the error.

**Comment by rarkins** [comment]
OK, that increases my suspicion of that dependency update. Are you using any custom npm registry?

**Comment by daprahamian** [comment]
yes, I am using a custom npm registry

**Comment by rarkins** [comment]
Also before deciding whether to roll back the dependency in the mainline, can you tell me what authentication method you're using for npm in renovate?

**Comment by daprahamian** [comment]
Using jenkins to run the CI build

shell command:
```
mkdir "$(pwd)/.tmpDir"
export TMPDIR="$(pwd)/.tmpDir"

export NODE_TLS_REJECT_UNAUTHORIZED=0

export RENOVATE_CONFIG_FILE="$(pwd)/config.js"

yarn add renovate@8.21.3

$(yarn bin)/renovate --token ${GITLAB_TOKEN} --log-level=debug
```

config.js is the following:

```
'use strict';

const commitMessage = require('./commit-message').default;
const yarnMaintenanceCommitMessage = require('./yarn-commit-message').default;

module.exports= {
  labels: ['refactor', 'renovate'],
  pinVersions: false,
  logLevel: 'verbose',
  onboarding: false,
  platform: 'gitlab',
  endpoint: *****, // my company's gitlab endpoint
  assignees: [45], // my assignee #
  maintainYarnLock: true,
  commitMessage,
  yarnMaintenanceCommitMessage,
  repositories: [
    // my repositories (approx. 23) here, as strings
  ],
};
```

Node version is `6.10.x`
Yarn version is `0.21.3`

We use Artifactory for our registry, and use the basic http authentication described here: https://www.jfrog.com/confluence/display/RTF/Npm+Registry#NpmRegistry-NpmPublish(DeployingPackages)

**Comment by destroyerofbuilds** [comment]
The issue stems from this _enhancement_ to `registry-auth-token` - https://github.com/rexxars/registry-auth-token/commit/d96d422c2d5ae14be7c1a2ac529e91f9947872c7

`registry-auth-token` now returns the value of `_auth` from `.npmrc` instead of `undefined` when there is no `_authToken` variable associated with a registry.

However, `registry-auth-token` is returning the type of the token as `Bearer`, which `_auth` is not.

`_auth` is the Base64 encoded version of a `username:password` string.

Instead, the type should be `Basic`.

Let me verify this locally with the latest `renovate` code.

**Comment by destroyerofbuilds** [comment]
I made the following change to `renovate`'s source code - https://github.com/singapore/renovate/blob/master/lib/api/npm.js#L19

```javascript
  const authInfo = registryAuthToken(regUrl);
  if (authInfo.type === `Bearer`) {
    authInfo.type = `Basic`;
  }
  const headers = {};
```

Authentication worked fine.

@daprahamian can we push this issue upstream to `registry-auth-token`?

@rarkins could we downgrade `renovate` until an upstream fix can be applied?

**Comment by destroyerofbuilds** [comment]
Also, for completeness sake, our global `npmrc` file is something like the following:

```
registry=http://artifactory.example.com/artifactory/api/npm/npm
@myco:registry=http://artifactory.example.com/artifactory/api/npm/npm-myco/
_auth = REDACTED
always-auth = true
//artifactory.example.com/artifactory/api/npm/npm-myco/:_password=OTHER_REDACTED
//artifactory.example.com/artifactory/api/npm/npm-myco/:username=jenkins
//artifactory.example.com/artifactory/api/npm/npm-myco/:always-auth=true
```

The `npm-myco` repository on Artifactory is where we keep private packages, while the `npm` repository on Artifactory is just a mirror of the official `npm` registry.

Authentication was working fine for our private packages because `registry-auth-token` was using the Base64 encoded version of the username and password from lines 5 and 6. However, authenticated requests to the `npm` repository on Artifactory were failing because the latest release of `registry-auth-token` now extracts out the value of `_auth` and treats it as a Bearer token, though it's actually a Basic auth value.

**Comment by rarkins** [comment]
@destroyerofbuilds so is rolling back `registry-auth-token` is preferable to you over patching it inside `renovate`?

**Comment by destroyerofbuilds** [comment]
For better or worse, I take a similar approach as @daprahamian, and `yarn install renovate@latest` in a Jenkins-based CI job triggered on a schedule.

So I don't, and here's the better or worse thing, maintain a fork of `renovate`, or lock down the CI jobs to a particular version. So, if this was what you were implying, I don't have a fork to apply a temporary patch.

I believe @daprahamian and I have already updated our jobs to lock down the `renovate` version.

If you were implying that we could patch the upstream `renovate` to switch the auth type, we could, but the problem is the other package, and I, personally, don't like the idea of implementing work around code in downstream projects.

**Comment by rarkins** [comment]
Actually I was more thinking that I'd add the sample code you provided to `renovate`, if it had no negative side effects, and remove it if/when it's fixed. But anyway, let's roll back the version for now and I'll push out a new `renovate`.

**Comment by destroyerofbuilds** [comment]
We've submitted https://github.com/rexxars/registry-auth-token/pull/17
