### ISSUE TITLE
Improve tmp directory use and cleanup

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#252]
`tmp` directories are used for `yarn` and `npm` lockfile generation.

Proposal 1: Reuse the same tmp dir per-repository to maximise `node_modules` reuse and speed
  * If npm/yarn caches are in use, does this make much improvement?
  * Could this result in any additional failure cases? (remembering we don't actually care what's in the `node_modules`, it's an unfortunate byproduct of getting the lock files)

Proposal 2: Clean up `tmp` dirs after each repository
  * For the case where `renovate` runs on a lot of repositories/package files, it's important that we don't keep accruing disk space until it's finished
  * I'm assuming that `tmp` is only removing these temporary directories after the full `renovate` run has finished

**Comment by rarkins** [comment]
https://github.com/singapore/renovate/pull/140

**Comment by destroyerofbuilds** [comment]
> I'm assuming that tmp is only removing these temporary directories after the full renovate run has finished

That is correct. If I remember correctly `tmp` hooks into `process.on('exit', ()=>{})`.

> do you think this default could be returned, as long as we have a configuration to disable tmp cleanup?

I probably wouldn't bother with adding an extra configuration option for disabling the manual calls to the cleanup function. As you noted, Windows is a minor use case (and only relevant to me because we use Windows for development where I work).

Long term it would be more beneficial to track down the issue that causes the cleanup function to throw an exception on Windows. Unless anyone else uses Windows with `renovate`, that work should probably fall on me, or one of my co-workers.
