### ISSUE TITLE
Clean up branches after merge (GitHub)

### ISSUE THREAD

**Issue by mbrevda** [singapore/renovate#428]
Branches opened by renovate should be automatically deleted after a merge (and perhaps, also, if the PR is closed).

**Comment by rarkins** [comment]
Thanks for the suggestion. Current approach is this:

1. For GitLab, they support the option to auto-delete branches after merge, so they will already be cleaned up
2. For GitHub, if Renovate is configured to automerge PRs, then the branch will be deleted
3. For GitHub, if users merge a Renovate PR manually, they (currently) need to click this button afterwards:

![image](https://user-images.githubusercontent.com/6311784/27820113-83e69bea-609d-11e7-8f8f-2c552348e546.png)

I'm setting this to pri4 priority due to its low impact (I assume).

**Comment by mbrevda** [comment]
`pri4` - the higher the better, right? 😛 For what it's worth, greenkeeper auto deletes merged branches (which I guess is where I stole the idea from).

**Comment by rarkins** [comment]
My priority labelling is a bit of a hack so that GitHub sorts them from most important to least :)

FWIW I think this would be a convenient feature to have, and if I'm working on related code and figure out a quick trick to achieve it, then it might be implemented before other higher-prioritised issues.

That said, my muscle memory is now trained to click the Delete Branch button immediately after merging so I doubt this feature would come into use for any of my repos.

**Comment by mbrevda** [comment]
I'm not sure if this is working properly. Renovate opened a PR two days ago to update a dependency. This dependency was updated via a PR from another branch, but renovate's PR is still open.

Shouldn't it have been closed?

p.s. I have scheduling on this repo, if that matters

**Comment by rarkins** [comment]
Renovate will currently only close its own open PRs if it detects that the branch is in conflict with the base branch. Otherwise we can't be sure whether it's a valid PR just waiting for its schedule.

Does the PR show up as in conflict? Would it do anything more if it were to be merged or is it essentially a null op now?

Can you let me know the branch so I can also check the logs?

**Comment by rarkins** [comment]
And I assume it wasn't a renovate PR that updated it in another branch?

**Comment by mbrevda** [comment]
> Renovate will currently only close its own open PRs if it detects that the branch is in conflict with the base branch

But at the very least, it should rebase it's branch against the base branch - no?

> Does the PR show up as in conflict?

No

> Would it do anything more if it were to be merged or is it essentially a null op now?

The PR still shows a diff, but it wouldn't effectively do anything if merged (as the diff is outdated, and has essentially already been applied).

> Can you let me know the branch so I can also check the logs?

sent via dm

> And I assume it wasn't a renovate PR that updated it in another branch?

Correct - this was a manually merge of **real code** 😉

**Comment by rarkins** [comment]
Thanks for the info - this outcome makes sense (although isn't desirable). To explain:

1. Renovate has a list of branches it knows *should* exist at that point in time - according to the current schedule - and it will create/update/rebase etc all of those
2. This branch/PR is no longer on that list so it's not going to get updated or rebased
3. Currently this doesn't get cleaned up because I haven't thought of logic that allows it to be sure that this isn't just a renovate branch that's "off schedule" right now.

By the way, this could be achievable if renovate kept state about every branch it's every created and why. In theory then you could do some type of comparing or reasoning to work out that this branch. But by not keeping state except for what's in GitHub itself, it keeps things pretty lightweight and flexible, so in edge cases like this it takes a bit of "extra logic" to infer the state.

I'll reopen this issue to reflect that's there's an edge case not yet fixed.

**Comment by mbrevda** [comment]
> this isn't just a renovate branch that's "off schedule" right now.

I'm not sure I understand. Can you explain?

**Comment by rarkins** [comment]
When renovate starts, it builds a list of packages to renovate and filters out any whose schedule is off at the time. It's done early for performance reasons but this means we don't "know"
Branch names of packages that are off-schedule. 

One way to solve this may be for to build the branches up until the last stage regardless of schedule and then skip applying them if schedule is off. This way it would be easier to detect these "orphans"
