### ISSUE TITLE
Linking to issues/PRs results in noisy references on a dependency's repo

### ISSUE THREAD

**Issue by not-an-aardvark** [singapore/renovate#478]
Hi,

First of all, thanks for working on this app -- it looks like a cool project.

When `renovate` makes a PR to update a dependency, it seems to include a list of commits, which also includes any link to issues that appear in the commit messages. From the perspective of a user of `renovate`, this seems like a useful behavior. However, since GitHub leaves a note on an issue whenever it's linked to from anywhere, this can get spammy for the maintainers of the dependency.

To illustrate the problem: We released a new version of ESLint today, and now this is appearing on many of our issues and PRs:

![](https://i.gyazo.com/27ea7fc2953b7a263c2af72990b50df8.png)

This isn't a big problem, but it's mildly annoying, and the list will only grow larger as more people start to use `renovate`. Notices like this are generally useful because they indicate when an issue is receiving a lot of attention, but having a bunch of autogenerated notices just adds noise, particularly if the issue in question is still open.

Of course, I don't want to stop you from creating the best experience for users of your app, but it would be nice if you could prevent this from happening somehow.

**Comment by rarkins** [comment]
Hi @not-an-aardvark,

Thanks for raising this issue, and especially so politely.

I think it's imperative that I need to balance the interests of "the community" vs providing features for users and in particular to be a good bot citizen. And you're right that the problem will only get worse as the number of renovate users grows.

I think that a good balance might be to disable changelog hyperlinking in renovate Pull Requests whenever repositories are *public*, and keep it for those that are private. That way you as an open source maintainer will only see such links in GitHub issues if they're from a private repository for which you also have access. Does that seem reasonable to you?

**Comment by not-an-aardvark** [comment]
Yes, that seems like a good solution and would solve the issue. Thanks!

**Comment by rarkins** [comment]
As discussed, I have pushed an update to `renovate` so that it only hyperlinks upstream issue numbers when the repository is private. After running this new version through the Renovate "GitHub App" I can confirm that existing hyperlinks have been restored back to plain text, for example in our own eslint upgrade PR #396 here. However the issues/PRs that were being pointed to still appear to have the same number of links as before. I don't know if GitHub keeps these forever or it just take a while for them to get cleaned up.

Note: I have *not* removed the hyperlinks in commit hashes. When I check such commit hash pages on GitHub (e.g. https://github.com/eslint/eslint/commit/e0f0101fb949cf1aae5dc825cde9650743f0d5d1) they don't seem to show anything so I'm hoping there's no "noise".
