### ISSUE TITLE
Clean up sibling branches after merge

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#508]
Hi! As i read the email, i got to try it. So, now i just finished with few merges, so i seen that was handled by Greenkeeper, but seems it isn't here.

For example, if you have multiple PRs of same library, when you merge the newest one, other should be close, i believe?

See [these PRs](https://github.com/tunnckoCore/es6-template/pulls?q=is%3Apr+is%3Aclosed). When i merged the PR for `nyc` 11, i thought PRs for 9 and 10 would be closed, but Renovate didn't so i closed them manually.

It will be great if it can handle such cases :)

Good job any way! :tada:

**Comment by rarkins** [comment]
@tunnckoCore yes, it should be doing that already. I'll take a look.

**Comment by rarkins** [comment]
Here's one example:
![image](https://user-images.githubusercontent.com/6311784/28449613-b0c625b2-6de1-11e7-87de-cd058a967c75.png)

It's showing your account closed the PR while the bot deleted the branch.  Was it less than 30 minutes before you closed the PR yourself manually? Renovate runs on a 30 minutes cycle so that should be the maximum bound it takes to clean up anything.

This approach is a tradeoff for simplicity - the only way to automatically close other PRs when a user merges another would be to be listening to webhooks and reacting, whereas renovate the CLI tools is designed to be installed/run from npm by anyone. It's likely I'll add webhooks to the *app* though to speed up cases like this though.

**Comment by tunnckoCore** [comment]
>  Was it less than 30 minutes before you closed the PR yourself manually?

mm probably, dont remember. i will see on monday
