### ISSUE TITLE
scoped package name missing in prBody 

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#518]
It seems the scoped package name is missing in the prBody, for example: https://github.com/ikatyang/generator-ts-jest/pull/9.

Thanks for the awesome tool. 👍

**Comment by rarkins** [comment]
Thanks for raising the issue. I noticed this yesterday and fixed it for the onboarding PR, but need to add the fix for regular PRs or make the fix more generic. It's "caused" by GitHub's smart hyperlinking of `@username` so needs some escaping added to bypass it.

Example fix: https://github.com/singapore/renovate/blob/master/lib/workers/repository/onboarding.js#L161-L162
