### ISSUE TITLE
Ignore forked repositories

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#541]
e.g. for people who have installed Renovate on all repos.

If a repo is a fork, and it doesn't have a `renovate.json` in it, then ignore it.

**Comment by charlike** [comment]
Hehe, that's great :) In any way, it is advisable to activate it one by one. Or in my case it that @tunnckoCore is now almost empty, so i transferring all my repos one by one after updating them, because i have too much things to update. It may be hard month of updating tons of things in that 300+ repos and actual npm packages, but i don't have much choice.

The mistake/damage was done in the moment that i activated GK for all repos. Because some old repos dont have proper badges, so probably most of them now show breaking, exactly because the PRs of GK, not because they are really broken.

In any way, i need to update all deps of them, because some packages are not touched for years - some of them are with out-dated deps, some of them STILL `dependencies: up-to-date` and `build: passing` for years, which is totally fantastic!
