### ISSUE TITLE
Commits summary of PRs

### ISSUE THREAD

**Issue by charlike** [singapore/renovate#595]
Few times noticed that "renovate (bot) referenced that issue from commit", i was surprised. Then realized that it is because the commits that it shows in opened prs.

![2017-08-03-12 26 20_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/28915103-bc342114-7846-11e7-889a-04cd5e5e29d1.png)
![2017-08-03-12 26 37_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/28915104-bc34c2ae-7846-11e7-8787-07893a09846d.png)

When some commit of dependency references some of its issues and your repo has same issue id.

The list of commits looks good that way, but maybe should think of some escaping. GK had another problem, it wraps the commit message in "`", probably for that reason, but when some of the commit messages includes "`" too, it was ugly.

**Comment by rarkins** [comment]
That's weird. Those issue numbers are meant to be escaped with backticks to prevent hyperlinking causing "noise" in public repos. 

How long ago did this last happen and can you link me to any public examples?

I disabled deliberate linking to upstream repos a few weeks ago after a guy in eslint noticed an annoying number of references to all their issues/PRs :-/

It should still be enabled for private repos because those should not be visible to maintainers of upstream public repos.

**Comment by charlike** [comment]
From noticed it probably in the 2nd day, but don't remember where. Screenshots are from before 17-20 days. As, about link, probably this one is good https://github.com/tunnckoCore/koa-better-body/pull/100. Hm, just noticed that really, there are backticks, but it seems to not escape them.

**Comment by charlike** [comment]
Cool! :)
