### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by SebastienElet** [singapore/renovate#66]
Hello,

It would be really awesome to support yarn and update the yarn.lock in each PR.

I don't know if this is doable with a javascript api or if this is in the scope of renovate (maybe this should be done by another bot/binary).

**Comment by rarkins** [comment]
Thanks for the suggestion. I haven't tried yarn yet but have been meaning to. I'll need to understand the relation between package.json versions and what's in yarn.lock before being able to confirm if there's a feasible way to support this.

**Comment by rarkins** [comment]
From their [docs](https://yarnpkg.com/en/docs/yarn-lock):

> Your yarn.lock file is auto-generated and should be handled entirely by Yarn. As you add/upgrade/remove dependencies with the Yarn CLI, it will automatically update your yarn.lock file. Do not edit this file directly as it is easy to break something.

So it says not to modify it in practice. In theory.. maybe

One question is: if you used this type of dependency updating service, would you still use ranges in package.json? 

Although even if you pin all direct dependencies from your package.json, I think the yarn lock file will include dependencies those use too (second tier dependencies), which are typically unpinned.

Another concept: even if none of your direct dependencies have version updates, some of their second tier dependencies might have received updates since the last time you ran yarn - and maybe some of those would be a really important patch, too.

**Comment by rarkins** [comment]
I think to do this we'd need to spawn yarn itself to see the updated yarn lock file. It's a change of current architecture (which is lightweight API calls only) but it's definitely achievable.

**Comment by SebastienElet** [comment]
The yarn.lock is like an npm shrinkwrap and pin every dependencies.
If renovate is able to rebuild it on each PR, this will be a nice speed increase for devs ! The long part in yarn is when you have to rebuild the yarn.lock, otherwise its blazing fast.

Technically, the upgrade could be done with [shelljs](https://github.com/shelljs/shelljs).

**Comment by rarkins** [comment]
Do you mean the time spent manually pulling a branch locally to run yarn and then commit an updated yarn lock file?

**Comment by SebastienElet** [comment]
The time to install packages will be reduced.

**Comment by rarkins** [comment]
I've been trying to catch up on what `yarn`'s exact behaviour is with its lock file. Seems there is/was confusion and bugs: https://github.com/yarnpkg/yarn/issues/570#issuecomment-257190341

My understanding from that is that `yarn` by default shouldn't rebuild the `yarn.lock` file unless a user performs an action that requires it (e.g. adding a new package, or forcing an update of packages).

Originally, I had thought your request in this issue was: "If `renovate` updates a repository's `package.json`, then you it should update the `yarn.lock` file too, if present". i.e. you were referring only to PRs that `renovate` creates. This requirement seems like something `renovate` should be doing, if it is to support repositories with `yarn` users.

A second requirement I then thought of was for `renovate` to force `yarn` to run update on the base branch of a repository and then submit a PR if anything has changed in `yarn.lock`. i.e. the {R is not changing anything in `package.json`, but checking if there any upstream updates for those dependencies' dependencies.

Are there any more `yarn`-related requirements you have in mind? e.g. `renovate` updating other PRs which it itself hasn't created?

**Comment by SebastienElet** [comment]
My need was only for PR created by `renovate` of course.

In the futur, `renovate` could also check other PR, but this is out of the scope of the project ATM.

I don't know `yarn` very well too, my company use it in dev actually but the goal is to replace `npm shrinkwrap` for production builds.

**Comment by rarkins** [comment]
Relevant: https://yarnpkg.com/en/docs/cli/generate-lock-entry

**Comment by rarkins** [comment]
Seems we'd need to run `yarn upgrade [package@version]`.

**Comment by hbetts** [comment]
I believe the two scenarios outlined by @rarkins [here](https://github.com/singapore/renovate/issues/66#issuecomment-275334237) cover the two cases I'm familiar with.

My `yarn.lock` file is updated when I manually add, remove, or upgrade a single dependency, and when I periodically run `yarn upgrade` ([without any arguments](https://yarnpkg.com/en/docs/cli/upgrade#toc-yarn-upgrade)) to upgrade dependency versions based on the existing semantic version ranges specified in my `package.json` file.

**Comment by hbetts** [comment]
On a related note, there has been [a discussion](https://github.com/yarnpkg/rfcs/issues/6) requesting `yarn` support a programmatic API. Already [someone has provided an example](https://github.com/yarnpkg/rfcs/issues/6#issuecomment-262860993) of needing to integrate with `yarn`, and not wanting to fork out to a sub-process.

**Comment by rarkins** [comment]
@hbetts thanks again for the feedback. There's a lot of cross-over with `yarn` in #31 too.

As you mention, your current manual approach is running `yarn upgrade` without arguments. This has the potential to upgrade multiple dependencies at once. If you had an automated system like renovate, would you prefer to upgrade dependencies one-per-branch or still stick to a single branch for all upgrades?

**Comment by rarkins** [comment]
I'm thinking of making the first step like this:

- Autodetect `yarn.lock` to enable our yarn feature
- Assume users are using ranges in `package.json` 
- Read `package.json` but do not modify/update it
- For each dependency in `package.json`, find the current pinned version in `yarn.lock`
- See if any versions from npm satisfy the range in `package.json` and are newer than the `yarn.lock` version
- If so, run `yarn update dependency@version`
- Commit the new `yarn.lock` file and create/update PR

Later, we can add the option of also detecting if ranges in `package.json` should be updated too (e.g. for a new major version), but that feature can be developed afterwards.

**Comment by rarkins** [comment]
@hbetts I know you like to keep ranges as wide as possible, but I don't like choice 1 above. The reality is that dependencies *do* get broken in minor versions and even patches. Even if your own tests don't detect such a break initially, keeping each dependency upgrade (i.e. `renovate` PR) separate would make tracing it back (e.g. using `git bisect`) easier.

Unless I'm missing something, an appropriate compromise would seem to be my original idea before I found out how `yarn` works practically. i.e. ranges in `package.json` remain same, but you can force update pinned version in `yarn.lock` one dependency at a time.

BTW I tested if running something like `yarn upgrade foo@^1.0.0` would have the desired effect of leaving `package.json` as `^1.0.0` but `yarn.lock` upgrading its pinned version from `1.0.0` to `1.1.0`. Unfortunately `yarn.lock` remained unchanged - I guess because `package.json` was not considered "dirty" so `yarn.lock` wasn't regenerated.

**Comment by rarkins** [comment]
I'm now reconsidering what "first stage" yarn support should look like and considering targeting it at apps not libraries. With an app, you may as well pin your `package.json` versions too because you're not worried about downstream users getting conflicts. So then this model would be:

- Pin/upgrade versions in `package.json` like regular `renovate` does today
- Make sure `yarn.lock` is updated each time

**Comment by destroyerofbuilds** [comment]
> If you run `yarn upgrade foo` then yarn will not only update foo to 1.1.0 in yarn.lock but will also update package.json to use version ^1.1.0. Isn't this undesirable to unnecessarily restrict the version ranges, especially if you're building a library that others will consume?

Yes, upgrading the minimum version of `foo` to `1.1.0` is unnecessarily strict. Furthermore it would necessitate a new version of the project being published, which would cause downstream project's to need to upgrade. Leading to lots of noise for no value.

> I really prefer to update one dependency at a time, both for initial testing as well as rollback.

That would be my preference as well.

> Bad?: Assuming that renovate is running frequently and always updating you to the latest version, this is essentially the same as pinning your versions

I would agree that this would be bad because it probably means additional complexity for `renovate` without any value added to the user's experience.

> @hbetts I know you like to keep ranges as wide as possible, but I don't like choice 1 above. The reality is that dependencies do get broken in minor versions and even patches. Even if your own tests don't detect such a break initially, keeping each dependency upgrade (i.e. renovate PR) separate would make tracing it back (e.g. using git bisect) easier.

I agree. Option 1, though easier, makes it unnecessarily more difficult to discover the specific upstream package that broken a project. I'm totally on board with one PR per change. (I hope that doesn't end up being too noisy, as some of my projects have ~1020 dependencies in their tree, but I guess we can find out :-) ).

**Comment by destroyerofbuilds** [comment]
> Single branch to force yarn install all packages at once

Something to keep in mind is that by re-generating the `yarn.lock` file, instead of updating a specific package within it, has the advantage of allowing `yarn` to optimize the dependency tree by eliminating duplicate packages.

**Comment by rarkins** [comment]
@SebastienElet @hbetts could you take a look at https://github.com/singapore/renovate/pull/93 ?

As described there, this PR adds the logic:
- If `package.json` is to be updated then we check if a `yarn.lock` exists
- If it exists, we run a "fresh" `yarn install` and commit the resulting `yarn.lock`

Hence it is not compatible with maintaining ranges in `package.json` because that functionality isn't supported in the existing `renovate` either. However this hopefully satisfies anyone who wants to (1) pin `package.json` dependencies, and (2) use a `yarn.lock` to pin sub-dependencies too.

**Comment by rarkins** [comment]
Now published to npm in version 8.6.0
