### ISSUE TITLE
`automerge: 'patch'` caused minor automerge

### ISSUE THREAD

**Issue by ikatyang** [singapore/renovate#713]
- renovate PR https://github.com/ikatyang/tslint-config-prettier-ext/pull/32
- renovate config https://github.com/ikatyang/tslint-config-prettier-ext/blob/master/renovate.json#L30.

Something I found in #712, may be related:

- `automergeEnable: true` -> `automerge: true`
  - looks fine
- `automergeEnable: false` -> removed
  - looks fine (implicit = `false`)
- `automergeEnable: true` -> removed
  - looks weird since the test cases are not changed
  - but these are counter-cases for my issue, not sure why
  - https://github.com/singapore/renovate/pull/712/files#diff-954f9c9d61202d9314a154fee9885985L131
  - https://github.com/singapore/renovate/pull/712/files#diff-954f9c9d61202d9314a154fee9885985L213
  - https://github.com/singapore/renovate/pull/712/files#diff-954f9c9d61202d9314a154fee9885985L308
- `automergeEnable: false` -> `automerge: true`
  - I didn't see this anywhere, maybe this issue is caused by some config conflicts?

**Comment by rarkins** [comment]
@ikatyang this one might be caused by config, but maybe also i need to tune the migration script.

I see in your `default` config that you have `automerge=minor`: https://github.com/ikatyang/renovate-config-ikatyang/blob/master/package.json#L47

This will get translated to `minor.automerge=true`.

When you then define `automerge=patch` in https://github.com/ikatyang/tslint-config-prettier-ext/blob/master/renovate.json#L30, it won't *delete* that `minor.automerge` setting and instead just *add* `patch.automerge`.

I have rewritten your `renovate.json` into a form that should avoid this. But I think I can also improve the migration logic to fix your current config too.

```
{
  "extends": "ikatyang:library",
  "packageRules": [
    {
      "packageNames": [
        "codelyzer",
        "prettier",
        "tslint",
        "tslint-consistent-codestyle",
        "tslint-divid",
        "tslint-eslint-rules",
        "tslint-immutable",
        "tslint-microsoft-contrib",
        "tslint-misc-rules",
        "tslint-plugin-ikatyang",
        "tslint-react",
        "vrsource-tslint-rules"
      ],
      "minor": {
        "automerge": false
      },
      "patch": {
        "automerge": true
      }
    }
  ]
}
```
