### ISSUE TITLE
Renovate not creating PR on Gitlab 9.5

### ISSUE THREAD

**Issue by IGZgustavomarin** [singapore/renovate#749]
I have a `renovate` process scheduled twice a week. Last time it ran I see that it created all branches, but it didn't create any PR (well, Merge Request in GitLab).

Between the last two runs, the main difference is that we updated our GitLab from 9.4.x to 9.5. Maybe it contains some uncompatible change in the API?

Here is the last run log as an example 

```
DEBUG: Checking if branch exists: renovate/all (repository=my-company-tools/service-template)
DEBUG: Branch doesn't exist (repository=my-company-tools/service-template)
DEBUG: Creating branch renovate/all (repository=my-company-tools/service-template)
ERROR: Error updating branch: Branch already exists (400) (repository=my-company-tools/service-template, dependencies=mongoose, branch=renovate/all)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.my-company.io",
         "hostname": "gitlab.my-company.io",
         "method": "POST",
         "path": "/api/v3/projects/my-company-tools%2Fservice-template/repository/branches",
         "protocol": "https:",
         "url": "https://gitlab.my-company.io/api/v3/projects/my-company-tools%2Fservice-template/repository/branches",
         "statusCode": 400,
         "statusMessage": "Bad Request",
         "headers": {
           "server": "nginx",
           "date": "Mon, 28 Aug 2017 08:56:04 GMT",
           "content-type": "application/json",
           "content-length": "35",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "b77704d1-6db7-4487-9a49-66b92ba03f0e",
           "x-runtime": "0.010988"
         }
       }
DEBUG: branchList=renovate/all (repository=my-company-tools/service-template)
DEBUG: Removing any stale branches (repository=my-company-tools/service-template)
DEBUG: Platform is not GitHub - returning (repository=my-company-tools/service-template)
 INFO: Finished repository (repository=my-company-tools/service-template)
 INFO: Renovate finished

```

**Comment by rarkins** [comment]
Based on your logs it looks like the "branchExists" check reports false when it should be true?

**Comment by IGZgustavomarin** [comment]
I've checked on GitLab and the branches were there.

**Comment by rarkins** [comment]
So the code that checks is wrong and returning a "false negative"

**Comment by rarkins** [comment]
Here's the function: https://github.com/singapore/renovate/blob/master/lib/api/gitlab.js#L135
URL will be like `projects/${config.repoName}/repository/branches/${branchName}`

Here's the docs: https://docs.gitlab.com/ce/api/branches.html#get-single-repository-branch

Says `GET /projects/:id/repository/branches/:branch`

So that looks OK. Maybe the encoding of the `/` in branch name? e.g. needs to be `%2F` now?

Can you try these queries?

`curl --header "PRIVATE-TOKEN: <something>"  https://gitlab.noet.io/api/v3/projects/my-company-tools%2Fservice-template/repository/branches/renovate/all`

`curl --header "PRIVATE-TOKEN: <something>"  https://gitlab.noet.io/api/v3/projects/my-company-tools%2Fservice-template/repository/branches/renovate%2Fall`

**Comment by IGZgustavomarin** [comment]
You are right, first call returns 404, second one returns the needed data.

**Comment by rarkins** [comment]
Before making any changes to Renovate code, I'd like to confirm:

1. This is not related to your environment only
2. Whether such a change can be applied to all previous releases or if we need to do version sniffing either of the api (we already distinguish between v3 and v4) or of gitlab releases

I saw some similar old issues here:
https://gitlab.com/gitlab-org/gitlab-ce/issues/12753
https://gitlab.com/gitlab-org/gitlab-ce/issues/22400

These seem to have been caused by proxies in front of gitlab rather than by gitlab itself. Can you confirm if you are connecting directly to gitlab or through an nginx or apache proxy?

**Comment by rarkins** [comment]
Easiest solution of course is to encode the slash with `%2F` for all gitlab servers.. if we can confirm that works.

@hbetts have you tried GitLab 9.5 yet?

**Comment by IGZgustavomarin** [comment]
I ran this `curl` from outside the network and then ssh'ing into the GitLab machine and the result is the same.

We've also updated from GitLab 9.5.1 to 9.5.2 and got the same result.

**Comment by rarkins** [comment]
Sounds like a 9.5 regression then. Next thing is to work out if escaping forward slashes in 9.4 and below will also work

**Comment by IGZgustavomarin** [comment]
works great! thanks!
