### ISSUE TITLE
Renovate Dockerfile FROM versions

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#780]
Branching out from Javascript/npm, this would mean that Renovate could be used to also "renovate" Docker base image dependencies too.

**Comment by rarkins** [comment]
If this gets enough +1's or at least one person willing to help define requirements, I can prioritise it.

**Comment by tn-osimis** [comment]
Hello,

I'm coming from the discussion on [Nick Janetakis's site](https://nickjanetakis.com/blog/docker-tip-18-please-pin-your-docker-image-versions#comment-3506042030), big thanks for your interest.

## Tentative requirements

Warning: I'm mostly visualizing a supposedly ideal end-game, one would obviously need to work backwards from this (assuming this is a desirable end-game at all) to produce a leaner plan (implementing everything at once would likely be a mistake).

### Local state gathering

- Scan for Docker builder definition files in directory hierarchy. Alternatively, use user-defined list to locate them.

### Upgrade decision

For each Dockerfile:

- Parse [`FROM` instruction](https://docs.docker.com/engine/reference/builder/#from) and extract image repository name and digest. Warn and ignore file if digest is missing (even if a tag is provided instead, see below).
- [Interrogate Docker registry](https://docs.docker.com/registry/spec/api/) to [retrieve list of tags](https://docs.docker.com/registry/spec/api/#listing-image-tags) available in the given image repository (default to interrogate Docker Hub if the registry is not specified explicitly in the repository name).
- Load versioning scheme for the image (see below). Default to [semantic versioning 2.0](http://semver.org/).
- Load user-defined version policy for the image (see below). Default to "always target the latest version".
- Load the current version identifier (see below).
- From the list of tags for version identifiers in the repository, determine if a new version matching the user version policy is available.
- If no new desirable version is available, check the digest from the Dockerfile against the digest reported by the registry for the version in question. If they differ, initiate the upgrade procedure. Optional: In certain cases where this is unexpected warn the user so they can complain upstream. For example: a tag for a full version identifier (in semver: X.Y.Z) should be immutable. This is in contrast to a tag for a partial version identifier (in semver: X.Y) which *can* be updated to point to new images over time.
- If a new desirable version is available, initiate the upgrade procedure.

### Upgrade procedure

- Pull target image using digest. This is important: using the tag for the version identifier instead could lead to a race condition where the tag is moved to target another image after we verified it (see above).
- If necessary: store version identifier somewhere depending on the approach used to map digests back to version identifiers.
- Rewrite the Dockerfile to include new digest.
- Launch user-defined test suite.
- Apply user-defined upgrade policy (see below).

At any point if a step fails the procedure stops and the user is notified.

## Dockerfile scan heuristics:

- File name matches `/.*[dD]ockerfile.*/` by default or a user-defined pattern.
- [First non-comment (`#`) line starts with either `FROM` or `ARG`](https://docs.docker.com/engine/reference/builder/#format). Alternatively or in addition, use third-party linter to confirm it is indeed a Dockerfile. Example: [dockerfilelint](https://github.com/replicatedhq/dockerfilelint).

## On ignoring tags

Support for tag-based references to images in `FROM` instructions (`foo:bar`) will probably be requested by some users but pushing for digest-based references (`foo@baz`) is desirable. Since the idea is that users don't have to think about this thanks to this tool, completely ignoring the presumably inferior tag-based approach (while pointing them out as warning output) sounds reasonable to me. Benefits include the ability to run deterministic builds (only insofar as the Docker builder is concerned, of course).

## Versioning schemes

Realistically there aren't too many schemes but compared to other ecosystems the Docker image ecosystem does not have any conventions and there will be funky things out there, so it will be somewhat necessary to cater for them.

At first it's reasonable to assume semver and reuse something like [npm version range syntax](https://docs.npmjs.com/misc/semver#advanced-range-syntax) for the user version policies.

Quite early it is important to be able to handle classic versioning schemes that do not respect semver. The npm syntax doesn't seem to preclude it, so if it is reused no special issues should be expected.

Later new syntax can be added to handle things like date/time-based versions and other things.

### Detection

Once we stop assuming semver we need to somehow detect which scheme is actually used in that image repository so we can sort version identifiers in order to answer questions like "is there a new version?".

Hack: Docker registries store the date and time at which an image was produced. It sounds reasonable to use that to sort tags at first, but obviously a maintenance update for an older but still supported version might appear after the latest version, leading to obvious issues and making the approach a bad idea long-term.

At first, look for a user-declared scheme in a configuration file then use simple heuristics to try and detect whether it looks like semver or a date or something else.

Later [more advanced approaches](https://gist.github.com/tn-osimis/13c656c9c7eaced2a70e56f16e5b56c4) can be used, but would be overkill for a first proposal.

## Version policies

The user must be able to specify what the desired target version is (as a function of the versioning scheme) in a simple text file (under source control). For example: "semver: latest stable minor version for major version X", "date: latest stable version of 2017 edition", "any: latest beta version".

Again, for semver [npm version range syntax](https://docs.npmjs.com/misc/semver#advanced-range-syntax) can be used, and other schemes can be handled later.

Default to target the latest stable version in any scheme.

## Retrieving current version identifier

Because we only have a digest from the Dockerfile we need to map it back to a version identifier we can compare to those we retrieve from tag names in the repository on the registry.

Ideas: Interrogate the registry (it might not have the image anymore, and there might not even be an API for this), store the current version in a local file checked in source control, store the current version as a comment in the Dockerfile, use a tag *in addition* to the digest in the `FROM` instruction.

Note: I'm not sure using a tag in addition to the digest in the `FROM` instruction is [officially supported](https://docs.docker.com/engine/reference/builder/#from), but the current behavior of the Docker builder is to [ignore it](https://github.com/moby/moby/issues/33165#issuecomment-300907297), which seems perfect for this use-case.

Opinion: Right now I like the use of a comment in the Dockerfile, or obviously the use of a tag name in addition to the digest if we're confident the current behavior of the Docker builder will not change in that regard (i.e. that it will keep ignoring it).

## Upgrade policies

The user must be able to specify what to do when a new desirable version is available. This policy can take the test results into account as well as upstream signals.

Example upstream signals:
- Potential breaking changes (e.g. in semver: major number bump).
- Way down the road: retrieve machine-readable info from the upstream source control repository.

Example upgrade policies:
- Report a diff (e.g. `git diff`) containing the digest update in the terminal or send it via email, Slack or anything else.
- Create new source control branch and issue pull/merge request (e.g. new git branch, commit digest update, push to arbitrary repository, issue corresponding GitHub/GitLab/Bitbucket/... pull/merge request).
- Commit digest update to source control immediately and push the commit to an arbitrary repository. Rebase or create merge commit if upstream moved. Optional: Always create merge commit (e.g. `--no-ff` in git).

Default to immediate commit for upgrades signaled as "stable". This might be controversial but in practice developers often can't do much more than run an integration test suite to increase confidence in a dependency upgrade. If accidents happen, it will encourage developers to write better automated tests, which is a good thing. Maybe do something else that is sensible for upgrades not signaled as "stable" (like strongly suggest to the user that they go look for and read the upstream release notes before merging even if automated tests passed).

Automatically generated commit messages and merge/pull request descriptions should contain useful information (e.g. new version, maybe the previous version, maybe the digests, maybe links to the Docker image repository page if available, arbitrary image metadata changes, possibly upstream release notes if available/retrievable, etc).

## Test runner configuration

The user should be able to provide a single command to begin testing. Some detection heuristics can be used to perhaps detect test runners. Note however that tests involving running Docker containers will very often be different from your day-to-day unit tests, so just trying `npm test` if a `package.json` file is found may or may not be a good idea. Using conventions works (e.g. specially named npm script or shell program).

## Out-of-the-box experience

By using conventions and automatic detection approaches for various elements required in the process, we can imagine a user just launching one command at the root of a code repository.

Without any configuration, Dockerfiles are detected, upgraded to the latest version, and tested.

## Disclaimer

This is the first time I try to think these requirements up and haven't had the chance to discuss this before, so do question and criticize them freely. It is indeed very likely some things are misguided at best and impossible at worst.

In addition, I shamelessly admit to not having researched Renovate at all - I fully expect that many things I suggest here would not be in line with the vision and architecture of the project. I hope this is still useful enough to spark constructive discussions and push this forward.

**Comment by rarkins** [comment]
Hi @tn-osimis, thanks for taking the time to contribute the great ideas here. I will need at least a few days to try to think through this all and follow up in details. Here are some initial thoughts:

Renovate's default behaviour is to create branch (ideally kicking off existing CI tests) and then raise a PR for humans to merge. But it also supports a kind of direct upgrade mode too where it can merge the change directly to `master` if tests pass (without PR). This covers 2/3 of your suggestions and this is very configurable (eg could be configured on a per-file basis).

We already support file discovery for `package.json` using an exact file match. The same could be done for `Dockerfile` but I'm not sure if GitHub's API is flexible enough to support the type of pattern you suggested. How common and important is it to support non-default file names?

Using digest rather than tags is a really interesting idea. It's creative thinking because as humans we wouldn't want to do that manually but if you're using automation.. why not? Downloading images every run would be too heavy though so we'd need a way to optimise that. Perhaps people would ultimately choose between either digest mode or pinned tag mode (eg x.y.z semver, such as 6.11.3 for `node`) pinned tag mode would likely be the initial approach due to its similarity to how npm semver works in the tool already. 

Adding a comment line in `Dockerfile`s as you suggest could be a reasonable requirement if we're using digests. 

Although it's rare, npm package versions can be "unpublished" within the first 24 hours so we handle this with a "rollback" feature. Sounds like this could be useful for docker hub too if images disappear without an upgrade.

**Comment by tn-osimis** [comment]
@rarkins Thanks for a quick initial response.

> How common and important is it to support non-default file names?

There is a relatively common "builder pattern" which consists in using two Docker builder definition files, often in the same directory and using different names. Other than that, I do not believe it is common (in my own experience at least).

Although it doesn't cover all cases, the recent [multi-stage builds](https://blog.alexellis.io/mutli-stage-docker-builds/) feature of the Docker builder removes the need for this pattern in a great majority of cases.

All-in-all, definitely don't consider this a blocking issue, especially for early prototypes.

> Downloading images every run would be too heavy though so we'd need a way to optimise that.

Oh I agree that wouldn't work. The registry obviously holds a map of tags to digests and I believe it exposes this relation through its API without requiring the client to download the data.

A cursory look at the reference documentation may give potential solutions:
- It seems like [issuing a `HEAD` request to blob resources](https://docs.docker.com/registry/spec/api/#blob) in order to retrieve the `Docker-Content-Digest` header value would be sufficient (input: tag, output: digest).
- The [manifest](https://docs.docker.com/registry/spec/api/#manifest) might be useful.

Clearly it would be great to have it embedded in the response to the request for the list of tags, but it doesn't seem to be possible. Still, issuing individual requests for each tag, especially with HTTP 2 when supported, shouldn't incur an unmanageable amount of overhead.

> pinned tag mode would likely be the initial approach due to its similarity to how npm semver works in the tool already

Regardless of my personal opinions there are a few things to consider if allowing this approach:

- There is no way to know if an image previously retrieved using a tag is the same as the one available in the registry at the time of the run, **even if the tag name is the same** (i.e. tags can and are often expected to be updated to point to new images).
- Because of this, you wouldn't be able to guarantee to the user that they have the latest desirable version, nor that everybody on the team is actually using the same version.

My opinion (which I'm sure you already inferred from my previous message): I think the status quo of targeting moving tags for partial versions (especially with semver) or moving "stable" tags and of hoping that things *usually* do not break (oh but when they do) is going to remain sufficient for many users and covers many requirements of "continuous dependency management" ("just remember to pull often"). Generating pull requests for larger jumps automatically only marginally improves on this situation IMO. In contrast, the mere possibility of having fully identical environments generated by a fully deterministic build process across all involved hosts (mostly dev laptops and CI hosts, but sometimes even staging and prod) is a giant leap forward. We can do it today, yet nobody does, and I think that is precisely because updating digests manually is too much of a burden. The prospect of a tool that would do it automatically is *extremely* attractive to us and I imagine for many other people.

> Adding a comment line in Dockerfiles as you suggest could be a reasonable requirement if we're using digests.

Yes. Again maybe consider specifying both tags and digests in the `FROM` instruction instead if it sounds like a stable approach, as I alluded to before. The idea of using a comment is really just the 100% safe bet in case better approaches fail.

> Although it's rare, npm package versions can be "unpublished" within the first 24 hours so we handle this with a "rollback" feature. Sounds like this could be useful for docker hub too if images disappear without an upgrade.

That's a very nice feature! Indeed I believe this can also happen in Docker registries.

Docker Hub in particular also removes older tags periodically and I imagine purges unreferenced images after that. In case that's important, it means the registry does not hold a full historical view of the versions of an image (though I don't think you need it).

**Comment by rarkins** [comment]
I agree that the digest pinning is the most desirable approach, and it's exciting if it's the type of improvement that's only really feasible with a tool/automation rather than by automation. 

One thing I didn't respond about earlier was testing. Renovate definitely isn't a "test tool" and defers that responsibility to CI. For npm packages that's kind of the best way anyway, but as you pointed out, typical CI tests may not really be effective at verifying a base image upgrade. I'm not sure if there's a good answer to this. I thought about modifying the test script (eg `travis.yml`) but then that would "break" the PR because it's not a change you'd want to merge to `master`. Maybe it needs more intelligent test runners than most use today, to target tests based on what changed.

**Comment by tn-osimis** [comment]
> One thing I didn't respond about earlier was testing. Renovate definitely isn't a "test tool" and defers that responsibility to CI. For npm packages that's kind of the best way anyway, but as you pointed out, typical CI tests may not really be effective at verifying a base image upgrade. I'm not sure if there's a good answer to this. I thought about modifying the test script (eg travis.yml) but then that would "break" the PR because it's not a change you'd want to merge to master. Maybe it needs more intelligent test runners than most use today, to target tests based on what changed.

Gotcha.

Honestly I was mostly differentiating between unit tests and integration tests in the context of automatically detecting a way to run integration tests. Because it is out-of-scope for Renovate (which is perfectly fine) we shouldn't worry about this here. It is definitely desirable that integration tests (which can definitely increase confidence in base image upgrades) be run as part of the CI pipeline (it's in the name!) so it's all good IMO.

**Comment by rarkins** [comment]
I'm ready to start work on an initial version. Some ideas/thoughts:

1. Restrict to filename `Dockerfile` for now
2. Support the image:tag@digest approach first
3. Support `FROM` only, not `ARG` yet
4. If the `FROM` line is not in this format, then the first thing we do is "Pin" it
   * e.g. `FROM node` will become something like `FROM node@sha:abcdefghijklmnop`
   * e.g. `FROM node:8.4.0` will become like `FROM node:8.4.0@sha:abcdefghijklmnop`
5. After a FROM line has a digest, it will continue to be updated whenever applicable
6. Public DockerHub only

Future functionality:
- Support customised filename search
- Support non-digest mode (no pinning)
- Support updating tags according to semver (e.g. from @8.4.0 to @8.4.1)
- Support custom registries
- Support registry authentication for private images

**Comment by rarkins** [comment]
Getting manifest: http://blog.tomecek.net/post/download-manifests-from-docker-hub/
e.g. https://registry.hub.docker.com/v2/library/node/manifests/8

https://forums.docker.com/t/get-image-digest-from-remote-registry-via-api/9480

https://stackoverflow.com/a/41830007/3005034

**Comment by rarkins** [comment]
Example for getting digest for `node:latest`:

```
$ REPOSITORY=library/node

$ TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$REPOSITORY:pull" | jq -r .token)

$ curl -s -D - -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://index.docker.io/v2/$REPOSITORY/manifests/latest | grep "Docker-Content-Digest"
```

**Comment by destroyerofbuilds** [comment]
I recently began exploring Docker by releasing my own `docker-hugo` image (using my personal GitLab account) - https://gitlab.com/hyper-expanse/docker-hugo/blob/master/Dockerfile#L2

I intentionally pinned the parent image, `alpine`, to a `<major>.<minor>` tag to improve the deterministic behavior of my build.

However, as @tn-osimis so elegantly described in his initial comment, a pinned semantic version is insufficient since tags are not immutable (which is in contrast to npm).

I would love to switch to using content hashes, but as you have both pointed out, managing that manually is really hard.

**Comment by destroyerofbuilds** [comment]
@tn-osimis props on your requirements comment. I found your requirements to be sufficiently detailed to capture my personal needs, while remaining easy to read.

**Comment by destroyerofbuilds** [comment]
> Load user-defined version policy for the image (see below). Default to "always target the latest version".

Since I'm still new to Docker, I'd personally like to see `renovate` automatically upgrade my `Dockerfile` to the latest patch or minor version, but submit a major version as a pull request.

Perhaps it won't make a difference. I don't really know how closely Docker publishers following SemVer.

I just know that I haven't learned how to validate my Docker image, so major versions will likely need my manual input to ensure breaking changes have been accounted for.

**Comment by rarkins** [comment]
@tn-osimis @destroyerofbuilds initial support for `Dockerfile` updates has been merged to master now. It will autodetect all `Dockerfile` files on GitHub, but needs manual provisioning if on GitLab (we haven't implemented a satisfactory file search there yet).

It will:
- Pin any FROM to use a digest if it's not already
- Update the Dockerfile FROM line any time it detects a new digest

I've added another 5 issues for future improvements (e.g. custom registry, authentication, custom file names, and semver support). Until Docker semver support is done here, you might want to use "open" tags like `node:8` instead of `node:8.4.1` if you wish Renovate to keep you updated with all 8.x releases.

**Comment by tn-osimis** [comment]
@rarkins I've been waiting to actually try it all out before replying but now I'll be away for a couple of weeks so it looks like it's going to be a little while more ;).

Really though: thank you for doing this. I (evidently) love this approach and your swift execution was impressive. I'll be thinking of an internal project I could target to showcase this to my teammates when I get back, and hopefully we can evaluate renovate seriously for all our projects that would benefit in the future.

@destroyerofbuilds Thanks for the comment; though that was the easy part ;). To answer your question regarding semver conventions for Docker images: the container image ecosystem is really an aggregate of many ecosystems following all kinds of versioning conventions (more often than not unrelated to semver) that usually match the upstream project conventions (which is the least surprising approach). I don't think one should expect this to change.
