### ISSUE TITLE
Excluded packages seem to be ignored

### ISSUE THREAD

**Issue by denkristoffer** [singapore/renovate#900]
Hey, it's very possible that this is a configuration issue on my side, but Renovate has upgraded and merged a package, `subscriptions-transport-ws`, that I thought would be exluded:

My config looks like this 

```json
"packageRules": [
  {
    "excludePackageNames": [
      "subscriptions-transport-ws"
    ]
  }
]
```

**Comment by rarkins** [comment]
The `excludePackageNames` instruction is only relevant to the package rule. e.g. it would let you define a pattern like 'subscriptions-' to match but then explicitly exclude `subscriptions-transport-ws`.

If you wish for `subscriptions-transport-ws` to never be upgraded, you can do it either of two ways:

#### package rule

```
"packageRules": [
{
  "packageNames": ["subscriptions-transport-ws"],
  "enabled": false
}
]
```

### ignoreDeps

```
  "ignoreDeps": ["subscriptions-transport-ws"]
```

`ignoreDeps` is obviously easier/clearer. I just included the package rule so that the way they work is hopefully clearer to you.
