### ISSUE TITLE
Running every lock file maintenance in sync with update schedule

### ISSUE THREAD

**Issue by Siilwyn** [singapore/renovate#901]
:wave: Hi there, I'm wondering if it's possible to schedule an update every month. I tried `on the last day of the month` but it seems to trigger an update every week instead: https://github.com/Siilwyn/semver-level-harmony

**Comment by rarkins** [comment]
Hi @Siilwyn 

The weekly PRs you see are "lock file maintenance". You can read a brief description [in the faq](https://github.com/singapore/renovate/blob/master/docs/faq.md#keep-lock-files-including-sub-dependencies-up-to-date-even-when-packagejson-hasnt-changed) but it sounds like you would want this disabled and get PRs for upgrades only. Please confirm if you wish to see these monthly or only get PRs if `package.json` needs updating, and I'll suggest your config change.

**Comment by Siilwyn** [comment]
Hi, thanks for the quick detailed reply!

I have a few small low maintenance modules, I'd like to keep their dependencies *and* lockfile up-to-date without too many PRs. Ideally it would be every 2-3 months but that's not possible yet. So for every month would it look like this?
```
{
  "pinVersions": false,
  "schedule": ["on the last day of the month"],
  "lockFileMaintenance": {
    "schedule": ["on the last day of the month"]
  }
}
```

**Comment by rarkins** [comment]
Yes, that config should switch lock file maintenance to being monthly.

FYI there's a bug with the third party library I use for schedule parsing and *last* day of the month doesn't work, but *first* does. I noticed this previously in the app's logs and so change last to first. So your schedule will work but don't be surprised to see it happening on the first day, not last.

Your schedule is still not perfect for your requirements though. You should expect to see one PR per updated dependency, plus the lock file maintenance PR. The problem is that once you merge the first PR, any others will then likely have merge conflicts in the lock file, and Renovate won't be running to fix/regenerate these automatically, so you'll need to do it yourself.

Is your idea situation that there's just a single PR per month, with all/any `package.json` upgrades + lock file updated too?

**Comment by Siilwyn** [comment]
> Is your ideal situation that there's just a single PR per month, with all/any package.json upgrades + lock file updated too?

Yes absolutely.

I didn't realize renovate will create a PR for each updated dependency. :0

**Comment by Siilwyn** [comment]
Realized I can group all packages like this and prevent conflicts like this, right?

```
{
  "lockFileMaintenance": {
    "schedule": ["on the first day of the month at 6 am"]
  },
  "packageRules": [
    {
      "packagePatterns": [".+"],
      "pinVersions": false,
      "schedule": ["on the first day of the month at 8 am"]
    }
  ]
}
```

**Comment by rarkins** [comment]
You can't specify *at* in a schedule because Renovate doesn't process repos at any exact time - it had a queue it services usually 1-2 times per hour. Hence it supports only before/after and not an exact "at".

Grouping them all together is easier, actually - just specify
```
  "groupName": "all"
```

Some months you may get only the lock file maintenance PR  and other months you might get another PR called "Renovate all packages". If you get two then you can just merge the second one and close the lock file maintenance one.

**Comment by rarkins** [comment]
```json
{
  "groupName": "all",
  "schedule": ["before 8am on the first day of the month"],
  "lockFileMaintenance": {
    "schedule": ["before 8am on the first day of the month"]
  }
}
```

**Comment by rarkins** [comment]
FYI in future it would be preferred if you can raise config queries here, too: https://github.com/renovateapp/config-help

**Comment by Siilwyn** [comment]
@rarkins cheers! Appreciate your help!
