### ISSUE TITLE
Default merge request body causes unintentional issue mentions on Gitlab

### ISSUE THREAD

**Issue by Autre31415** [singapore/renovate#954]
Gitlab 10+ introduced a bug that causes issues to be mentioned in overly sensitive ways.

Example:

`<h4>4.0.0</h4>` will mention issue 400

The bug has a related issue [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/38473) which was actually posted by a Renovate user.

According to that issue they're planning to have it fixed for milestone 10.3 with a date range of Nov 8-Dec 22. Since that ranges between 1-2 months away I'm thinking it might be a good idea to alter the default merge request body to remove the linking headers for version numbers until the regression in gitlab is fixed to prevent unintentional issue mentions polluting gitlab feeds over that time.

**Comment by rarkins** [comment]
I'm fine to accept a PR for this, as I'm not 100% sure how wide we need to cast the net. Is it only within headings?

We already do some PR body search/replace here, for example: https://github.com/singapore/renovate/blob/master/lib/api/gitlab.js#L382-L384

And we already do some massaging of PR bodies prior to that due to *GitHub* autolinking problems: https://github.com/singapore/renovate/blob/8fc61e35bcec54a22bc0c93450d47819e5246b79/lib/workers/pr/index.js#L132-L138

Perhaps the solution here could be if there is a character in another language that *looks* like the full stop but tricks GitLab?

**Comment by Autre31415** [comment]
I'm still seeing issues being mentioned in merge requests. Perhaps the safest way to ensure this behavior doesn't continue is just bolding the version numbers for now instead of using headings.

**Comment by rarkins** [comment]
OK, updated code on the way
