### ISSUE TITLE
support `.renovaterc` which can be YAML or JSON

### ISSUE THREAD

**Issue by olstenlarck** [singapore/renovate#969]
Just for the sake of conventions? In fact, i always use JSON, but thinking to switch to YAML, since it is a lot more clean and you don't need to think about commas and such shits :D  It would be great even if package.json one day can be just YAML... :pray: 

In fact, to support this the only thing that you may need is [pretty-config resolver](https://github.com/tunnckoCore/hela/blob/master/src/pretty-config.js), which i'll release in day or two. It is a lot more small and sane than the `cosmiconfig` alternative.

**Comment by rarkins** [comment]
Would that definitely be the file name and not renovate.yaml?

**Comment by rarkins** [comment]
- [x] I'm fine with the name `.renovaterc`
- [ ] File format - YAML, JSON or both?

Answering my own question, the file format for .XXXXXXXrc files is definitely not a convention. e.g. `.npmrc` is "ini" file format and `.babelrc` is JSON.

I guess we *can* support YAML and JSON (e.g. parse JSON first then try YAML if it fails) so is there any downside other than the chance of confusion? It's probably better to keep the same file name (instead of `.renovaterc.json`, `.renovaterc.yaml`) because we need to use the platform API to get each file and this will save us at least one round trip.

**Comment by rarkins** [comment]
One downside: editors won't know which syntax highlighting to use if no file extension. Looks like babel may support optional extensions too, but this can be annoying for us when using the remote API.

**Comment by destroyerofbuilds** [comment]
> One downside: editors won't know which syntax highlighting to use if no file extension.

Which is a big reason `npm` went with `package-lock.json` over the Yarn convention of `yarn.lock`, so as to leverage the natural behavior of IDEs, and other tools, to behave a particular way because of the file extension.

How does going with `.renovaterc` over the existing file name improve the user experience?

**Comment by olstenlarck** [comment]
Really worth nothing to have support for with and without extension. As about the highlighting, yea i'm agree but any IDE have support to define what files what syntax to use - for example i in my vscode have defined that all `.*rc` should be highlighted as .json syntax.

All this is just because i have tons ([really](https://github.com/tunnckoCore/rollup-config-tunnckocore), before year or two i hated that approach, but that's a must tools to work well with the IDEs) of dotfiles per project, and want all of them to be the same - for example all to be just `.toolrc` with json syntax, or all to be with `.json` extension, or all to be with `.yml` and etc.

As about conventions.. Mostly all `.*rc` files are json.

> I guess we can support YAML and JSON (e.g. parse JSON first then try YAML if it fails) so is there any 

yea, that's how pretty-config handles it. Btw it is released as `@tunnckocore/pretty-config` for now and is here (fully working): https://github.com/charlike/pretty-config/blob/master/src/index.mjs

**Comment by rarkins** [comment]
Because we now obtain a full file list from each repo during init, it is effectively zero cost for us to support multiple file names and check for them in order. I'm considering supporting:
- renovate.json for legacy reasons, maybe to deprecate one day)
- .renovaterc (json or yaml)
- .renovaterc.json
- .renovaterc.yaml

That way if you want a "dot file" then you can have it, and if you also want a file extension then you can have it too. 

Another question is which filename/format to default to during onboarding. I maybe prefer yaml over json by a little however the app is written in JS so maybe there's better synergy with json.

**Comment by rarkins** [comment]
I would not need a third party resolver for this though as file list is essentially local and logic is simple once decided on

**Comment by olstenlarck** [comment]
Yup, sounds good. It would be great when lands :)

**Comment by anantakrishna** [comment]
Any plans to update https://docs.renovatebot.com/configuration-options/ so that people would know about `yaml` alternative?

**Comment by anantakrishna** [comment]
#1142 trickily skips YAML support, only adds another names for JSON configs. Quite a misleading thing.

**Comment by rarkins** [comment]
Confirmed: we support only JSON format
